### ISSUE TITLE
Neighbor struct element, uint8_t too small for rad or degrees

### ISSUE THREAD

**Issue by xgroleau** [MISTLab/BittyBuzz#9]
We are starting to add positioning between our agents.

The bbzneighbors_elem_t  struct uses uint8_t for the distance, azimuth and elevation. For the distance it can be manageable and use the distance as centimetres(with a max of 2.55 m) or decimetres (with a max distance of 25.5m). Though for the azimuth and elevation, the angle in the doc is in rad. Though using a uint8_t for rads is definitely not ideal (only the values 1,2 and 3 would be possible values since it's an int, unless we quantify it). So we though using angles in degrees, though again, the value could only go from 0 - 255, so 256-359 is not possible. It may be possible to use Q2.6 for rads, though the user would need to convert it in the buzz script everytime since it's pushed as an int in the bbvm.

https://github.com/MISTLab/BittyBuzz/blob/9cdaa16b86d2f009ad58a31078745fcfad30d2de/src/bittybuzz/bbzneighbors.h#L98

I check the zooids code for an example, and there is a possible overflow on angle since it's in degrees.

Where it is calculated in degrees
https://github.com/MISTLab/BittyBuzz/blob/9cdaa16b86d2f009ad58a31078745fcfad30d2de/src/zooids/lib/src/functions.c#L202

When it get casted as a uint8_t
https://github.com/MISTLab/BittyBuzz/blob/9cdaa16b86d2f009ad58a31078745fcfad30d2de/src/zooids/lib/src/bbzzooids.c#L107

Using floats or uint16_t would remove this problem. I don't know if it's a trivial modification in the codebase.

**Comment by Belkharym** [comment]
It should be possible to add an other option to make use of floats in the swarm primitives where needed.

The reason they were not was because we initially wanted to make BittyBuzz compact enough to fit on KiloBots, which don't have a way to know the bearing of the signal, only the range. So we decided to compromise on this to be able to fit the VM on the RAM.

But now that it is also used on robots with more resources, I can definitely see the need to have the option to have floats instead.

This change shouldn't be too hard to implement. We already have support for 16-bit floats in the VM itself, so we just have to add the right macros where needed.

**Comment by xgroleau** [comment]
Using actual floats as swarm primitives and add them to the  bbzneighbors_elem_t  instead of fixed point with uint16_t would definitely be useful to us since a lot of MCU have an FPU and would fix the uint8_t restriction on the neighbor struct for rads or degrees. 

Just to be clear, will this feature be added in the main repo or we should fork the project?

**Comment by Belkharym** [comment]
It should be added very soon to the repo.

**Comment by beltrame** [comment]
The comme was merged. @xgroleau can you check if this solves the issue?

**Comment by xgroleau** [comment]
Yep this resolved it, you can close the issue. Thanks!
